export type QuizLevel = "easy" | "medium" | "hard";

export type QuizItem = {
  id: number;
  english: string;
  french: string;
  level: QuizLevel;
  accepted?: string[];
};

export const QUIZ_ITEMS: QuizItem[] = [
  {
    id: 1,
    english: "Hello",
    french: "bonjour",
    level: "easy",
  },
  {
    id: 2,
    english: "Good evening",
    french: "bonsoir",
    level: "easy",
  },
  {
    id: 3,
    english: "Please",
    french: "s'il vous plaît",
    level: "easy",
    accepted: ["s il vous plait"],
  },
  {
    id: 4,
    english: "Thank you",
    french: "merci",
    level: "easy",
  },
  {
    id: 5,
    english: "Excuse me",
    french: "excusez-moi",
    level: "easy",
  },
  {
    id: 6,
    english: "Where is the bathroom?",
    french: "où sont les toilettes ?",
    level: "medium",
    accepted: ["ou sont les toilettes", "ou sont les toilettes?"],
  },
  {
    id: 7,
    english: "How much does it cost?",
    french: "combien ça coûte ?",
    level: "medium",
    accepted: ["combien ca coute", "combien ca coute?"],
  },
  {
    id: 8,
    english: "I would like a coffee",
    french: "je voudrais un café",
    level: "medium",
    accepted: ["je voudrais un cafe"],
  },
  {
    id: 9,
    english: "I don't understand",
    french: "je ne comprends pas",
    level: "medium",
  },
  {
    id: 10,
    english: "Can you help me?",
    french: "pouvez-vous m'aider ?",
    level: "medium",
    accepted: ["pouvez vous m'aider", "pouvez vous m'aider?"],
  },
  {
    id: 11,
    english: "The weather is beautiful today",
    french: "il fait beau aujourd'hui",
    level: "hard",
    accepted: ["il fait beau aujourd hui"],
  },
  {
    id: 12,
    english: "I have been learning French for two years",
    french: "j'apprends le français depuis deux ans",
    level: "hard",
    accepted: ["j apprends le francais depuis deux ans"],
  },
  {
    id: 13,
    english: "Could you repeat that more slowly?",
    french: "pourriez-vous répéter plus lentement ?",
    level: "hard",
    accepted: ["pourriez vous repeter plus lentement"],
  },
  {
    id: 14,
    english: "I'm looking forward to meeting you",
    french: "j'ai hâte de te rencontrer",
    level: "hard",
    accepted: ["j ai hate de te rencontrer"],
  },
  {
    id: 15,
    english: "Let's take a break",
    french: "prenons une pause",
    level: "medium",
  },
  {
    id: 16,
    english: "Good luck",
    french: "bonne chance",
    level: "easy",
  },
  {
    id: 17,
    english: "See you tomorrow",
    french: "à demain",
    level: "easy",
    accepted: ["a demain"],
  },
  {
    id: 18,
    english: "I would like to reserve a table",
    french: "je voudrais réserver une table",
    level: "hard",
    accepted: ["je voudrais reserver une table"],
  },
  {
    id: 19,
    english: "What's your name?",
    french: "comment t'appelles-tu ?",
    level: "medium",
    accepted: ["comment t appelles tu", "comment t'appelles-tu"],
  },
  {
    id: 20,
    english: "It's a pleasure",
    french: "enchanté",
    level: "easy",
  },
  {
    id: 21,
    english: "Good morning",
    french: "bonjour",
    level: "easy",
  },
  {
    id: 22,
    english: "Good night",
    french: "bonne nuit",
    level: "easy",
  },
  {
    id: 23,
    english: "See you later",
    french: "à plus tard",
    level: "easy",
    accepted: ["a plus tard"],
  },
  {
    id: 24,
    english: "Yes",
    french: "oui",
    level: "easy",
  },
  {
    id: 25,
    english: "No",
    french: "non",
    level: "easy",
  },
  {
    id: 26,
    english: "Maybe",
    french: "peut-être",
    level: "easy",
    accepted: ["peut etre"],
  },
  {
    id: 27,
    english: "I'm sorry",
    french: "désolé",
    level: "easy",
    accepted: ["desole"],
  },
  {
    id: 28,
    english: "You're welcome",
    french: "de rien",
    level: "easy",
  },
  {
    id: 29,
    english: "My name is...",
    french: "je m'appelle...",
    level: "easy",
  },
  {
    id: 30,
    english: "Nice to meet you",
    french: "ravi de vous rencontrer",
    level: "easy",
  },
  {
    id: 31,
    english: "I am American",
    french: "je suis américain",
    level: "easy",
    accepted: ["je suis americain"],
  },
  {
    id: 32,
    english: "Do you speak English?",
    french: "parlez-vous anglais ?",
    level: "easy",
    accepted: ["parlez vous anglais", "parlez vous anglais?"],
  },
  {
    id: 33,
    english: "I don't know",
    french: "je ne sais pas",
    level: "easy",
  },
  {
    id: 34,
    english: "I am hungry",
    french: "j'ai faim",
    level: "easy",
  },
  {
    id: 35,
    english: "I am thirsty",
    french: "j'ai soif",
    level: "easy",
  },
  {
    id: 36,
    english: "How are you?",
    french: "comment ça va ?",
    level: "easy",
    accepted: ["comment ca va", "comment ca va?"],
  },
  {
    id: 37,
    english: "Very well",
    french: "très bien",
    level: "easy",
    accepted: ["tres bien"],
  },
  {
    id: 38,
    english: "I'm tired",
    french: "je suis fatigué",
    level: "easy",
    accepted: ["je suis fatigue"],
  },
  {
    id: 39,
    english: "I love it",
    french: "j'adore",
    level: "easy",
  },
  {
    id: 40,
    english: "That's great",
    french: "c'est génial",
    level: "easy",
    accepted: ["c est genial"],
  },
  {
    id: 41,
    english: "What's this?",
    french: "qu'est-ce que c'est ?",
    level: "medium",
    accepted: ["qu est ce que c est", "qu est ce que c est?"],
  },
  {
    id: 42,
    english: "Where do you live?",
    french: "où habites-tu ?",
    level: "medium",
    accepted: ["ou habites tu", "ou habites tu?"],
  },
  {
    id: 43,
    english: "I live in New York",
    french: "j'habite à New York",
    level: "medium",
    accepted: ["j habite a New York", "j habite a new york"],
  },
  {
    id: 44,
    english: "What time is it?",
    french: "quelle heure est-il ?",
    level: "medium",
    accepted: ["quelle heure est il", "quelle heure est il?"],
  },
  {
    id: 45,
    english: "It's one o'clock",
    french: "il est une heure",
    level: "medium",
  },
  {
    id: 46,
    english: "I would like a glass of water",
    french: "je voudrais un verre d'eau",
    level: "medium",
  },
  {
    id: 47,
    english: "Can I have the menu?",
    french: "puis-je avoir le menu ?",
    level: "medium",
    accepted: ["puis je avoir le menu", "puis je avoir le menu?"],
  },
  {
    id: 48,
    english: "The bill, please",
    french: "l'addition, s'il vous plaît",
    level: "medium",
    accepted: ["l addition s il vous plait"],
  },
  {
    id: 49,
    english: "I need a taxi",
    french: "j'ai besoin d'un taxi",
    level: "medium",
  },
  {
    id: 50,
    english: "Where is the train station?",
    french: "où est la gare ?",
    level: "medium",
    accepted: ["ou est la gare", "ou est la gare?"],
  },
  {
    id: 51,
    english: "I would like to buy a ticket",
    french: "je voudrais acheter un billet",
    level: "medium",
  },
  {
    id: 52,
    english: "How far is it?",
    french: "c'est à quelle distance ?",
    level: "medium",
    accepted: ["c est a quelle distance", "c est a quelle distance?"],
  },
  {
    id: 53,
    english: "Turn left",
    french: "tournez à gauche",
    level: "medium",
    accepted: ["tournez a gauche"],
  },
  {
    id: 54,
    english: "Turn right",
    french: "tournez à droite",
    level: "medium",
    accepted: ["tournez a droite"],
  },
  {
    id: 55,
    english: "Go straight ahead",
    french: "allez tout droit",
    level: "medium",
  },
  {
    id: 56,
    english: "I'm looking for a hotel",
    french: "je cherche un hôtel",
    level: "medium",
    accepted: ["je cherche un hotel"],
  },
  {
    id: 57,
    english: "Do you have any rooms?",
    french: "avez-vous des chambres ?",
    level: "medium",
    accepted: ["avez vous des chambres", "avez vous des chambres?"],
  },
  {
    id: 58,
    english: "One night",
    french: "une nuit",
    level: "easy",
  },
  {
    id: 59,
    english: "Two nights",
    french: "deux nuits",
    level: "easy",
  },
  {
    id: 60,
    english: "Do you accept credit cards?",
    french: "acceptez-vous les cartes de crédit ?",
    level: "medium",
    accepted: ["acceptez vous les cartes de credit", "acceptez vous les cartes de credit?"],
  },
  {
    id: 61,
    english: "Where can I park?",
    french: "où puis-je me garer ?",
    level: "medium",
    accepted: ["ou puis je me garer", "ou puis je me garer?"],
  },
  {
    id: 62,
    english: "The wifi password",
    french: "le mot de passe wifi",
    level: "medium",
  },
  {
    id: 63,
    english: "I need a doctor",
    french: "j'ai besoin d'un médecin",
    level: "medium",
    accepted: ["j ai besoin d un medecin"],
  },
  {
    id: 64,
    english: "I am allergic",
    french: "je suis allergique",
    level: "medium",
  },
  {
    id: 65,
    english: "Call the police",
    french: "appelez la police",
    level: "medium",
  },
  {
    id: 66,
    english: "I'm lost",
    french: "je suis perdu",
    level: "medium",
  },
  {
    id: 67,
    english: "Could you take a photo?",
    french: "pourriez-vous prendre une photo ?",
    level: "medium",
    accepted: ["pourriez vous prendre une photo", "pourriez vous prendre une photo?"],
  },
  {
    id: 68,
    english: "It is too expensive",
    french: "c'est trop cher",
    level: "medium",
  },
  {
    id: 69,
    english: "Do you have a vegetarian option?",
    french: "avez-vous une option végétarienne ?",
    level: "medium",
    accepted: ["avez vous une option vegetarienne", "avez vous une option vegetarienne?"],
  },
  {
    id: 70,
    english: "I'm just looking",
    french: "je regarde seulement",
    level: "medium",
  },
  {
    id: 71,
    english: "What's the Wi-Fi?",
    french: "quel est le wifi ?",
    level: "medium",
    accepted: ["quel est le wifi", "quel est le wifi?"],
  },
  {
    id: 72,
    english: "Can I try this on?",
    french: "je peux essayer ?",
    level: "medium",
    accepted: ["je peux essayer", "je peux essayer?", "je peux essayer ça", "je peux essayer ca"],
  },
  {
    id: 73,
    english: "I need a size medium",
    french: "j'ai besoin d'une taille moyenne",
    level: "medium",
    accepted: ["j ai besoin d une taille moyenne"],
  },
  {
    id: 74,
    english: "Where is the nearest pharmacy?",
    french: "où est la pharmacie la plus proche ?",
    level: "medium",
    accepted: ["ou est la pharmacie la plus proche", "ou est la pharmacie la plus proche?"],
  },
  {
    id: 75,
    english: "I'd like to make a reservation",
    french: "je voudrais faire une réservation",
    level: "medium",
    accepted: ["je voudrais faire une reservation"],
  },
  {
    id: 76,
    english: "What do you recommend?",
    french: "que recommandez-vous ?",
    level: "medium",
    accepted: ["que recommandez vous", "que recommandez vous?"],
  },
  {
    id: 77,
    english: "I'm in a hurry",
    french: "je suis pressé",
    level: "medium",
    accepted: ["je suis presse"],
  },
  {
    id: 78,
    english: "Let's go",
    french: "allons-y",
    level: "easy",
    accepted: ["allons y"],
  },
  {
    id: 79,
    english: "Wait a moment",
    french: "attendez un instant",
    level: "easy",
  },
  {
    id: 80,
    english: "I will be back",
    french: "je reviens",
    level: "easy",
  },
  {
    id: 81,
    english: "I'm cold",
    french: "j'ai froid",
    level: "easy",
  },
  {
    id: 82,
    english: "I'm hot",
    french: "j'ai chaud",
    level: "easy",
  },
  {
    id: 83,
    english: "It's raining",
    french: "il pleut",
    level: "easy",
  },
  {
    id: 84,
    english: "It's sunny",
    french: "il fait soleil",
    level: "easy",
  },
  {
    id: 85,
    english: "Do you like it?",
    french: "ça te plaît ?",
    level: "medium",
    accepted: ["ca te plait", "ca te plait?"],
  },
  {
    id: 86,
    english: "I like it a lot",
    french: "j'aime beaucoup",
    level: "easy",
  },
  {
    id: 87,
    english: "I'm not sure",
    french: "je ne suis pas sûr",
    level: "medium",
    accepted: ["je ne suis pas sur"],
  },
  {
    id: 88,
    english: "I agree",
    french: "je suis d'accord",
    level: "easy",
  },
  {
    id: 89,
    english: "I disagree",
    french: "je ne suis pas d'accord",
    level: "medium",
  },
  {
    id: 90,
    english: "Can we sit here?",
    french: "on peut s'asseoir ici ?",
    level: "medium",
    accepted: ["on peut s asseoir ici", "on peut s'asseoir ici"],
  },
  {
    id: 91,
    english: "Do you have change?",
    french: "vous avez de la monnaie ?",
    level: "medium",
    accepted: ["vous avez de la monnaie", "vous avez de la monnaie?"],
  },
  {
    id: 92,
    english: "Where are you from?",
    french: "tu viens d'où ?",
    level: "easy",
    accepted: ["tu viens d ou", "tu viens d'ou", "tu viens d ou?"],
  },
  {
    id: 93,
    english: "I am from the United States",
    french: "je viens des États-Unis",
    level: "medium",
    accepted: ["je viens des Etats-Unis", "je viens des Etats Unis"],
  },
  {
    id: 94,
    english: "Could you write it down?",
    french: "pourriez-vous l'écrire ?",
    level: "medium",
    accepted: ["pourriez vous l ecrire", "pourriez vous l ecrire?"],
  },
  {
    id: 95,
    english: "I'm learning French",
    french: "j'apprends le français",
    level: "easy",
    accepted: ["j apprends le francais"],
  },
  {
    id: 96,
    english: "Please speak more slowly",
    french: "parlez plus lentement, s'il vous plaît",
    level: "medium",
    accepted: ["parlez plus lentement s il vous plait"],
  },
  {
    id: 97,
    english: "That's enough",
    french: "ça suffit",
    level: "easy",
    accepted: ["ca suffit"],
  },
  {
    id: 98,
    english: "I need help",
    french: "j'ai besoin d'aide",
    level: "easy",
  },
  {
    id: 99,
    english: "Do you have a map?",
    french: "vous avez un plan ?",
    level: "medium",
    accepted: ["vous avez un plan", "vous avez un plan?"],
  },
  {
    id: 100,
    english: "I am here on vacation",
    french: "je suis ici en vacances",
    level: "medium",
  },
  {
    id: 101,
    english: "I will call you later",
    french: "je t'appellerai plus tard",
    level: "hard",
    accepted: ["je t appellerai plus tard"],
  },
  {
    id: 102,
    english: "Let's meet at noon",
    french: "retrouvons-nous à midi",
    level: "hard",
    accepted: ["retrouvons nous a midi"],
  },
  {
    id: 103,
    english: "I have to go now",
    french: "je dois y aller maintenant",
    level: "medium",
  },
  {
    id: 104,
    english: "I'm not available",
    french: "je ne suis pas disponible",
    level: "medium",
  },
  {
    id: 105,
    english: "I will send you an email",
    french: "je t'enverrai un email",
    level: "hard",
  },
  {
    id: 106,
    english: "Could you wait for me?",
    french: "peux-tu m'attendre ?",
    level: "medium",
    accepted: ["peux tu m attendre", "peux tu m attendre?"],
  },
  {
    id: 107,
    english: "I'm running late",
    french: "je suis en retard",
    level: "medium",
  },
  {
    id: 108,
    english: "I will be there in five minutes",
    french: "j'arrive dans cinq minutes",
    level: "hard",
    accepted: ["j arrive dans cinq minutes", "j'arrive dans cinq minutes"],
  },
  {
    id: 109,
    english: "I don't have time",
    french: "je n'ai pas le temps",
    level: "medium",
  },
  {
    id: 110,
    english: "We need to decide",
    french: "il faut décider",
    level: "hard",
    accepted: ["il faut decider"],
  },
  {
    id: 111,
    english: "It depends",
    french: "ça dépend",
    level: "medium",
    accepted: ["ca depend"],
  },
  {
    id: 112,
    english: "That's not possible",
    french: "ce n'est pas possible",
    level: "medium",
    accepted: ["ce n est pas possible"],
  },
  {
    id: 113,
    english: "I'm worried",
    french: "je suis inquiet",
    level: "hard",
    accepted: ["je suis inquiet"],
  },
  {
    id: 114,
    english: "Take your time",
    french: "prends ton temps",
    level: "medium",
  },
  {
    id: 115,
    english: "It's a good idea",
    french: "c'est une bonne idée",
    level: "easy",
    accepted: ["c est une bonne idee"],
  },
  {
    id: 116,
    english: "I'm not used to it",
    french: "je n'y suis pas habitué",
    level: "hard",
    accepted: ["je n y suis pas habitue"],
  },
  {
    id: 117,
    english: "I'll think about it",
    french: "je vais y réfléchir",
    level: "hard",
    accepted: ["je vais y reflechir"],
  },
  {
    id: 118,
    english: "Let's continue",
    french: "continuons",
    level: "easy",
  },
  {
    id: 119,
    english: "Can you explain that again?",
    french: "peux-tu réexpliquer ?",
    level: "medium",
    accepted: ["peux tu reexpliquer", "peux tu reexpliquer?"],
  },
  {
    id: 120,
    english: "I need to practice more",
    french: "j'ai besoin de pratiquer davantage",
    level: "hard",
  },
];
